spring:
  sql.init.mode: never
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DRINKIT_POSTGRES_URL:}
    username: ${DRINKIT_POSTGRES_USERNAME:}
    password: ${DRINKIT_POSTGRES_PASSWORD:}
    hikari:
      auto-commit: false

# Remove Jooq logo & tip of the day log
logging:
  level:
    org.jooq.Constants: off