version: 2

updates:
  # Github Dependabot will find all gradle dependencies in gradle/libs.versions.toml
  # https://docs.github.com/fr/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#gradle
  - package-ecosystem: 'gradle'
    directory: ''/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 5
    commit-message:
      prefix: "[GRADLE-UPDATE]"
    labels:
      - 'gradle'
      - 'version update'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: "[GITHUB-ACTION-UPDATE]"
    labels:
      - 'github-actions'
      - 'version update'