spring:
  application.name: drinkit
  profiles:
    active: dev
    include: security
  sql.init.mode: never

server:
  port: ${PORT:8080}
  servlet:
    context-path: /drinkit

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always
  info:
    git:
      enabled: true
      mode: full
    build:
      enabled: true
    java:
      enabled: true

springdoc:
  api-docs:
    path: /openapi/api-docs
    enabled: false
  swagger-ui:
    path: /openapi/ui
    enabled: false
  show-actuator: true

# Remove Jooq logo & tip of the day log
logging:
  level:
    org.jooq.Constants: off