spring:
  application.name: drinkit
  profiles:
    active: dev

server:
  port: ${PORT:8080}
  servlet:
    context-path: /drinkit
    session:
      cookie:
        http-only: true
        secure: true
        name: SESSIONID
        same-site: strict
      tracking-modes: cookie
      timeout: 15m

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always
  info:
    git:
      enabled: true
      mode: full
    build:
      enabled: true
    java:
      enabled: true

springdoc:
  api-docs:
    path: /openapi/api-docs
    enabled: false
  swagger-ui:
    path: /openapi/ui
    enabled: false
  show-actuator: true