version: "3.8"

volumes:
  postgresql-data:

services:
  postgresql:
    image: postgres:16.1
    ports:
      - "5432:5432"
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "drinkit"
      POSTGRES_PASSWORD: "drinkit"