openapi: 3.0.3
info:
  title: Drink It API
  description: Drink It Apis for frontend/backend communication
  version: 1.0.0
servers:
  - url: http://127.0.0.1:8080
    description: Dev server
tags:
  - name: cellars
    description: Operations on cellars

paths:
  /drinkit/api/cellars:
    get:
      operationId: getCellars
      tags:
        - cellars
      summary: Get cellars
      description: |
        Returns all cellars you allow to see (owner or allowed from other users)
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: 'cellarsResponse.yaml#/components/schemas/CellarsResponse'