openapi: 3.0.3
info:
  title: common components for cellar api
  version: 1.0.0
  x-fragment: true
paths: {}
components:
  schemas:
    CellarsResponse:
      type: object
      required:
        - cellars
      properties:
        cellars:
          type: array
          minItems: 0
          maxItems: 20
          items:
            $ref: '#/components/schemas/CellarResponse'

    CellarResponse:
      type: object
      required:
        - id
        - name
        - location
      properties:
        id:
          $ref: 'common.yaml#/components/schemas/CellarId'
        name:
          type: string
          minLength: 1
          maxLength: 100
          example: "My cellar in Paris"
        location:
          $ref: 'common.yaml#/components/schemas/CityLocation'