openapi: 3.0.3
info:
  title: common components for cellar api
  version: 1.0.0
  x-fragment: true
paths: {}
components:
  schemas:
    CellarsResponse:
      type: object
      required:
        - cellars
      properties:
        cellars:
          type: array
          minItems: 0
          maxItems: 20
          items:
            $ref: '#/components/schemas/CellarResponse'

    CellarResponse:
      type: object
      required:
        - id
        - name
        - location
      properties:
        id:
          type: string
          format: cellar-id
          minLength: 24
          maxLength: 24
          pattern: '[\da-fA-F]{24}'
          example: 659ee3164b1d53340c4f7608
        name:
          type: string
          minLength: 1
          maxLength: 100
          example: "My cellar in Paris"
        location:
          $ref: '#/components/schemas/CityLocationResponse'

    CityLocationResponse:
      type: object
      required:
        - city
        - country
        - point
      properties:
        city:
          type: string
          example: Paris
        country:
          $ref: '#/components/schemas/CountryResponse'
        point:
          $ref: '#/components/schemas/PointResponse'

    CountryResponse:
      type: object
      required:
        - name
        - code
      properties:
        name:
          type: string
          example: France
        code:
          type: string
          minLength: 2
          maxLength: 2
          example: FR

    PointResponse:
      type: object
      required:
        - longitude
        - latitude
      properties:
        longitude:
          type: number
          minimum: -180.0
          maximum: 180.0
        latitude:
          type: number
          minimum: -90.0
          maximum: 90.0