email.sender.enabled: true

spring:
  mail:
    host: ${DRINKIT_EMAIL_HOST:smtp.gmail.com}
    port: ${DRINKIT_EMAIL_PORT:587}
    username: ${DRINKIT_EMAIL_USERNAME:}
    password: ${DRINKIT_EMAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true